apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: couchbaseclusters.couchbase.database.couchbase.com
spec:
  group: couchbase.database.couchbase.com
  names:
    kind: CouchbaseCluster
    plural: couchbaseclusters
    shortNames:
    - couchbase
    - cbc
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            adminConsoleServices: {}
            antiAffinity:
              type: boolean
            authSecret:
              minLength: 1
              type: string
            baseImage:
              type: string
            buckets:
              items:
                properties:
                  conflictResolution: {}
                  enableFlush: {}
                  enableIndexReplica: {}
                  evictionPolicy: {}
                  ioPriority: {}
                  memoryQuota:
                    minimum: 100
                    type: integer
                  name:
                    pattern: ^[a-zA-Z0-9._\-%]*$
                    type: string
                  replicas: {}
                  type:
                    enum:
                    - couchbase
                    - ephemeral
                    - memcached
                    type: string
                required:
                - name
                - type
                - memoryQuota
                type: object
              type: array
            cluster:
              properties:
                autoFailoverTimeout:
                  maximum: 3600
                  minimum: 1
                  type: integer
                dataServiceMemoryQuota:
                  minimum: 256
                  type: integer
                indexServiceMemoryQuota:
                  minimum: 256
                  type: integer
                indexStorageSetting:
                  enum:
                  - plasma
                  - memory_optimized
                  type: string
                searchServiceMemoryQuota:
                  minimum: 256
                  type: integer
              required:
              - dataServiceMemoryQuota
              - indexServiceMemoryQuota
              - searchServiceMemoryQuota
              - indexStorageSetting
              - autoFailoverTimeout
              type: object
            exposeAdminConsole:
              type: boolean
            paused:
              type: boolean
            servers:
              items:
                properties:
                  dataPath:
                    type: string
                  indexPath:
                    type: string
                  name:
                    minLength: 1
                    pattern: ^[-_a-zA-Z0-9]+$
                    type: string
                  pod:
                    properties:
                      automountServiceAccountToken:
                        type: boolean
                      couchbaseEnv:
                        type: object
                      labels:
                        type: object
                      nodeSelector:
                        type: object
                      resources:
                        properties:
                          limits:
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                              storage:
                                type: string
                            type: object
                          requests:
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                              storage:
                                type: string
                            type: object
                        type: object
                      tolerations:
                        items:
                          properties:
                            effect:
                              type: string
                            key:
                              type: string
                            operator:
                              type: string
                            tolerationSeconds:
                              type: integer
                            value:
                              type: string
                          required:
                          - key
                          - operator
                          - value
                          - effect
                          type: object
                        type: array
                    type: object
                  services:
                    minLength: 1
                    type: array
                  size:
                    minimum: 1
                    type: integer
                required:
                - size
                - name
                - services
                - dataPath
                - indexPath
                type: object
              minLength: 1
              type: array
            version:
              type: string
          required:
          - baseImage
          - version
          - authSecret
          - cluster
          - servers
  version: v1beta1
